version: "3.7"
services:
  api_service:
    build: .
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - postgresql_db
    links:
      - postgresql_db:postgresql_db
    secrets:
      - postgres_password
      - jwt_secret
      - spotify_client_secret
  postgresql_db:
    image: "postgres:latest"
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: soundmate
      POSTGRES_USER: soundmate
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
    secrets:
      - postgres_password
secrets:
  postgres_password:
    file: ./postgres_password.txt
  spotify_client_secret:
    file: ./spotify_client_secret.txt
  jwt_secret:
    file: ./jwt_secret.txt
