spring:
  datasource:
    url: jdbc:postgresql://${PG_HOST}:5432/${PG_DB_NAME}
    username: ${PG_USERNAME}
    password: ${PG_PASSWORD}
  liquibase:
    change-log: classpath:/db/changelog/changelog-master.xml
soundmate:
  jwtSecret: ${JWT_SECRET}
  jwtExpirationDays: 30
  spotifyClientId: 83bf8873115447d893923470b70d209a
  spotifyClientSecret: ${SPOTIFY_CLIENT_SECRET}


