spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/soundmate
    username: postgres
    password: ${PG_PASSWORD}

soundmate:
  jwtSecret: ${JWT_SECRET}
  jwtExpirationDays: 30
  spotifyClientId: 83bf8873115447d893923470b70d209a
  spotifyClientSecret: ${SPOTIFY_CLIENT_SECRET}

